### ISSUE TITLE
copy images from foundationify/assets subfolders to foundationify/dist/assets flattened and optimized

### ISSUE THREAD

**Issue by DOMUSNETWORK** [lukebussey/foundationify#12]
I dont really know if I've approved this right, just started using grunt and this is my first project I'm playing with in github and my first post all at once :)
What I was trying to achieve is to divide my products into folders with their images inside and their variants images into subfolders for the purpose of easy maintenance while everything is organized as it would appear on the actual shop, first thing I wanted to do is to copy recursively all the images starting from foundationify/assets/** and into dist/assets/ while making them all flattened inside dist/assets, next I wanted to erase the folders which they're structured from to be able to use shopify theme app and sync to my store safely. 

What I've done to make this work is just a couple of changes in the Gruntfile.js file.
(fileDiff symbols:[ - ] code removed, [ + ] code added, [ 'blank' ] original code.)

==================================

[CLEAN: @@ -44,7 +44,13 @@]
             dist: [
                 '.tmp',
                 '<%= yeoman.dist %>/*'
[ - ]            ]
[ + ]            ],
[ + ]            distDir: { 
[ + ]                src: ['<%= yeoman.dist %>/assets/*'],
[ + ]                filter: function(fp) {
[ + ]                    return grunt.file.isDir(fp);
[ + ]                }
[ + ]            }
         },

==================================

[IMAGEMIN: @@ -107,7 +113,7 @@]
            dist: {
                files: [{
                    expand: true,
                    cwd: '<%= yeoman.app %>/assets',
[ - ]                   src: '{,*/}*.{png,jpg,jpeg}',
[ + ]                   src: '**/*.{png,jpg,jpeg}', 
                    dest: '<%= yeoman.dist %>/assets'
                }]
            }

==================================

[COPY: @@ -145,7 +151,7 @@ & @@ -158,10 +164,17 @@]
           dist: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= yeoman.app %>',
                    dest: '<%= yeoman.dist %>',
                    src: [
[ - ]                        'assets/*',
[ + ]                        '!assets/*',
                        'config/*',
                        'layout/*',
                        'snippets/*',
                        'templates/*',
                    ]
                },{
                    expand: true,
                    cwd: '<%= yeoman.app %>/components/font-awesome/font',
                    dest: '<%= yeoman.dist %>/assets',
                    src: [
                        '*'
                    ]
[ - ]                }]
[ + ]                },{ 
[ + ]                    expand: true,
[ + ]                    flatten: true,
[ + ]                    src: ['<%= yeoman.app %>/assets/**'],
[ + ]                    dest: '<%= yeoman.dist %>/assets',
[ + ]                    filter: 'isFile'
[ + ]                }]
            },
        }

==================================

[grunt.registerTask('build', ... @@ -180,7 +193,8 @@]

   grunt.registerTask('build', [
        'clean:dist',
        'compass:dist',
        'cssmin',
        'imagemin',
        'uglify',
[ - ]        'copy'
[ + ]        'copy',
[ + ]        'clean:distDir'
    ]);

==================================

another thing worth mentioning is that I've updated 'grunt-contrib-imagemin', it made some strange error of some kind which I can't remember what it said and updating it solved this.

==================================

Hope it helps someone, maybe there is a better solution, or something I've missed, as I mentioned, I'm really noob at this and I'll be happy to hear some alternative way, maybe something related to sync plugin, which I haven't tested yet, the issue with this solution is while shopify theme app is running and you do "grunt build" it still builds the folders which it copied the images from and only later deletes them, so while the app is open and listening for the dist folder it gives an upload error since it recognizing a folder inside assets, not a big deal, still works even without "force deploy" but it's kinda annoying and I believe there is a better solution which I currently lack the experience to figure out.

cheers to you all,
Ilia luk.

**Comment by Leland** [comment]
Closing this due to age. If still something you're aiming to get integrated, please comment and let me know! Thanks!
