### ISSUE TITLE
Font Awesome not loaded

### ISSUE THREAD

**Issue by admanami** [lukebussey/foundationify#18]
Also a problem with the demo site: http://foundationify.myshopify.com/

**Comment by admanami** [comment]
To fix, I uploaded fonts to Shopify's 'assets' folder, then changed the $fa-font-path in:
/foundationify-master/bower_components/fontawesome/scss/_variables.scss

NB - This seems to do nothing:
/foundationify-master/styles/_settings.scss
// Foundationify Settings

$fontAwesomePath: ".";

**Comment by Leland** [comment]
Turns out that this was an error with Grunt's path for FontAwsesome's font files. I'm guessing that FontAwesome dropped the hyphen from their name a while back, and changed the folder name from "font" to "fonts."
